version: "3.9"
services:
  twenty-front:
    build: 
      context: ../..
      dockerfile: ./infra/dev/front/Dockerfile
    ports:
      - "3001:3001"
      - "6006:6006"
    environment:
      REACT_APP_API_URL: ${FRONT_REACT_APP_API_URL}
      REACT_APP_AUTH_URL: ${FRONT_REACT_APP_AUTH_URL}
    volumes:
      - ../../front:/app/front
      - twenty_node_modules_front:/app/front/node_modules
    depends_on:
      - postgres
  twenty-server:
    build:
      context: ../..
      dockerfile: ./infra/dev/server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../server:/app/server
      - twenty_node_modules_server:/app/server/node_modules
    environment:
      SERVER_DATABASE_URL: ${SERVER_DATABASE_URL}
    depends_on:
      - postgres
  twenty-docs:
    build:
      context: ../..
      dockerfile: ./infra/dev/docs/Dockerfile
    ports:
      - "5001:3000"
    volumes:
      - ../../docs:/app/docs
      - twenty_node_modules_docs:/app/docs/node_modules
  postgres:
    build: ./postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  db_data:
  twenty_node_modules_front:
  twenty_node_modules_server:
  twenty_node_modules_docs: