version: "3.9"
services:
  twenty-dev:
    build: 
      context: ../..
      dockerfile: ./infra/dev/twenty-dev/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6006:6006"
    volumes:
      - ../..:/app
      - /app/front/node_modules
      - /app/server/node_modules
    depends_on:
      - postgres
  twenty-docs:
    build:
      context: ../..
      dockerfile: ./infra/dev/twenty-docs/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ../../docs:/app/docs
      - twenty_node_modules_docs:/app/docs/node_modules
  postgres:
    container_name: twenty_postgres
    build: ./postgres
    volumes:
    - twenty_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=twenty
      - POSTGRES_PASSWORD=twenty
      - POSTGRES_DB=default
    ports:
      - "5432:5432"
volumes:
  twenty_db_data:
    name: twenty_db_data
  twenty_node_modules_front:
  twenty_node_modules_server:
  twenty_node_modules_docs: