version: "3.9"
services:
  twenty:
    build: 
      context: ../..
      dockerfile: ./infra/dev/twenty/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6006:6006"
    volumes:
      - ../../front:/app/front
      - ../../server:/app/server
      - ../../infra:/app/infra
    depends_on:
      - postgres
  postgres:
    build: ./postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
volumes:
  db_data: