version: "3.9"
services:
  twenty:
    build: 
      context: ../..
      dockerfile: ./infra/dev/twenty/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "6006:6006"
    volumes:
      - ../..:/app
      - twenty_node_modules_root:/app/node_modules
      - twenty_node_modules_front:/app/front/node_modules
      - twenty_node_modules_server:/app/server/node_modules
    depends_on:
      - postgres
  postgres:
    build: ./postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
volumes:
  db_data:
  twenty_node_modules_root:
  twenty_node_modules_front:
  twenty_node_modules_server: