name: 'CI Chromatic'

on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: http://127.0.0.1:3000/graphql
      REACT_APP_AUTH_URL: http://127.0.0.1:3000/auth
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Front / Write .env
        run: |
          cd front
          touch .env
          echo "REACT_APP_API_URL: $REACT_APP_API_URL" >> .env
          echo "REACT_APP_AUTH_URL: $REACT_APP_AUTH_URL" >> .env
      - name: Front / Install Dependencies
        run: cd front && yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./front
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
        