name: CI Docs
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Docs / Install Dependencies
        run: cd docs && yarn
      - name: Docs / Build Documentation
        run: cd docs && yarn build
