name: CI Docs
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Check for redundant workflow run
        run: |
          HEAD_SHA=$(git rev-parse HEAD^)
          if [ "$HEAD_SHA" != "${{ github.event.pull_request.head.sha }}" ]; then
            echo "HEAD SHA and Pull Request HEAD SHA do not match, cancelling run"
            echo "GitHub has scheduled a newer workflow run already."
            exit 1
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Docs / Install Dependencies
        run: cd docs && yarn
      - name: Docs / Build Documentation
        run: cd docs && yarn build
