name: CI Server
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
      - run: echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
      - run: echo "GITHUB_REF: ${{ github.ref }}"
      - uses: actions/checkout@v3
        if: github.head_ref == 'main'
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: actions/checkout@v3
        if: github.head_ref != 'main'
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Server / Install Dependencies
        run: cd server && yarn install
      - name: Server / Run linter
        run: cd server && yarn lint
      - name: Server / Run jest tests
        run: |
          cd server && yarn test
