name: CI Server
on:
  push:
    branches:
      - main
  pull_request_target:
jobs:
  server-test:
    runs-on: ubuntu-latest
    env:
      PG_DATABASE_URL: postgres://postgres:postgrespassword@localhost:5432/test?connection_limit=1
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: postgrespassword
          POSTGRES_DB: test
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'push'
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request_target'
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Server / Install Dependencies
        run: cd server && yarn install
      - name: Server / Run linter
        run: cd server && yarn lint
      - name: Server / Run jest tests
        run: |
          cd server && yarn test
      - name: Server / Run e2e tests
        run: |
          cd server && yarn test:e2e-ci
